name: CI/CD Pipeline - Tasks Service

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # 1. ni idea
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 2. Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login en Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3

        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Construir y publicar imagen Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/insightflow-tasks:latest, ${{ secrets.DOCKER_USERNAME }}/insightflow-tasks:latest${{ github.sha }}

      # 5. Desplegar en Render
      - name: Deploy to Render
        run: |
          curl -X POST \`${{ secrets.RENDER_DEPLOY_HOOK }}\`